# Generated by Django 5.2.4 on 2025-07-29 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_dob'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE Users
                ALTER COLUMN role SET DEFAULT 'user'
            """,
            reverse_sql='''
                ALTER TABLE Users
                ALTER COLUMN role SET DEFAULT 'super_admin'
            '''
        )
    ]
