# Generated by Django 5.2.4 on 2025-08-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
          migrations.RunSQL(
            sql='''
                CREATE TABLE Album_Song (
                id SERIAL PRIMARY KEY,
                album_id INTEGER NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
                song_id INTEGER NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
                UNIQUE(album_id, song_id)
            );
            ''',
            reverse_sql='''
                DROP TABLE IF EXISTS Album_Song
            '''
        )
    ]
