# Generated by Django 5.2.4 on 2025-08-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_not_null'),
    ]

    operations = [
         migrations.RunSQL(
            sql="""
                ALTER TABLE Song
                RENAME TO songs;
            """,
            reverse_sql="""
                ALTER TABLE Songs
                RENAME TO Song;
            """
        )
    ]
