# Generated by Django 5.2.4 on 2025-08-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_table_name'),
    ]

    operations = [
         migrations.RunSQL(
            sql="""
                ALTER TABLE Songs
                ADD COLUMN title VARCHAR(255) NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE Songs
                DROP COLUMN title
            """
        )
    ]
