# Generated by Django 5.2.4 on 2025-08-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_add_title'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE Songs
                DROP COLUMN album_name;
            """,
            reverse_sql="""
                ALTER TABLE Songs
                ADD COLUMN album_name VARCHAR(255);
            """
        )
    ]
