# Generated by Django 5.2.4 on 2025-07-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_add_column_no_of_album_released'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE Artists 
                RENAME COLUMN manager TO manager_id;
            """,
            reverse_sql="""
                ALTER TABLE Artists 
                RENAME COLUMN manager_id TO manager;
            """
        )
    ]
