# Generated by Django 5.2.4 on 2025-07-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_rename_column_manager_id'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE Artists
                ALTER COLUMN first_release_year TYPE DATE USING first_release_year::DATE;
            """,
            reverse_sql="""
                ALTER TABLE Artists
                ALTER COLUMN first_release_year TYPE TIMESTAMP WITHOUT TIME ZONE USING first_release_year::TIMESTAMP WITHOUT TIME ZONE;
            """
        )
    ]
