# Generated by Django 5.2.4 on 2025-07-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_release_year_type_datetime_to_date'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE Artists 
                RENAME COLUMN no_of_album_released TO no_of_albums_released;
            """,
            reverse_sql="""
                ALTER TABLE Artists 
                RENAME COLUMN no_of_albums_released TO no_of_album_released;
            """
        )
    ]
