# Generated by Django 5.2.4 on 2025-08-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_rerename_column_no_of_albums_released'),
    ]

    operations = [
         migrations.RunSQL(
            sql="""
                UPDATE Artists SET first_release_year = NULL;
                ALTER TABLE Artists 
                ALTER COLUMN first_release_year TYPE INT USING first_release_year::INT;
            """,
            reverse_sql="""
                UPDATE Artists SET first_release_year = NULL;
                ALTER TABLE Artists 
                ALTER COLUMN first_release_year TYPE DATE USING first_release_year::DATE;
            """
        )
    ]
