# Generated by Django 5.2.4 on 2025-08-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_alter_first_release'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE artists SET first_release_year = NULL;
                ALTER TABLE artists
                ALTER COLUMN first_release_year TYPE INT
                USING EXTRACT(YEAR FROM first_release_year)::INT;
            """,
            reverse_sql="""
                UPDATE artists SET first_release_year = NULL;
                ALTER TABLE artists
                ALTER COLUMN first_release_year TYPE DATE
                USING TO_DATE(first_release_year::TEXT, 'YYYY');
            """
    )

    ]
