# Generated by Django 5.2.4 on 2025-08-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_auto_20250808_0745'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE artists
                ADD CONSTRAINT first_release_year_range
                CHECK (first_release_year BETWEEN 1900 AND 2025);
            """,
            reverse_sql="""
                ALTER TABLE artists
                DROP CONSTRAINT first_release_year_range;
            """
        )

    ]
