# Generated by Django 5.2.4 on 2025-07-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                CREATE TABLE IF NOT EXISTS Artists (
                    id SERIAL PRIMARY KEY,
                    user_id INT NOT NULL,
                    artist_name VARCHAR(255) NOT NULL,
                    first_release_year TIMESTAMP,
                    created_at TIMESTAMP DEFAULT NOW(),
                    updated_at TIMESTAMP DEFAULT NOW(),
                    FOREIGN KEY (user_id) REFERENCES Users ON DELETE CASCADE
                )
            ''',
            reverse_sql='''
                DROP TABLE IF EXISTS Artists
            '''
        )
    ]
