# Generated by Django 5.2.4 on 2025-07-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                CREATE TABLE IF NOT EXISTS Song (
                    id SERIAL PRIMARY KEY,
                    artist_id INT NOT NULL,
                    album_name VARCHAR(255) NOT NULL,
                    genre VARCHAR(255) NOT NULL ,
                    song_link VARCHAR(255),
                    song_cover VARCHAR(255),
                    created_at TIMESTAMP DEFAULT NOW(),
                    updated_at TIMESTAMP DEFAULT NOW(),
                    FOREIGN KEY (artist_id) REFERENCES Artists ON DELETE CASCADE
                )
            ''',
            reverse_sql='''
                DROP TABLE IF EXISTS Artists
            '''
        )
    ]
