# Generated by Django 5.2.4 on 2025-07-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql='''
                DO $$
                BEGIN
                    if not exists (select 1 from pg_type where typname='user_role') then
                        CREATE TYPE user_role AS ENUM ('super_admin','artist_manager','artist','user');
                    end if;
                END$$;
                
                CREATE TABLE IF NOT EXISTS Users (
                    id SERIAL PRIMARY KEY,
                    email VARCHAR(100) UNIQUE NOT NULL,
                    password VARCHAR(255) NOT NULL,
                    first_name VARCHAR(100) NOT NULL,
                    last_name VARCHAR(100) NOT NULL,
                    role user_role NOT NULL DEFAULT 'super_admin',
                    phone VARCHAR(10),
                    gender VARCHAR(10),
                    address VARCHAR(100),
                    dob TIMESTAMP,
                    created_at TIMESTAMP DEFAULT NOW(),
                    updated_at TIMESTAMP DEFAULT NOW()
                );
                ''',
            reverse_sql='''
                DROP TABLE if exists Users
            '''

        )
    ]
