# Generated by Django 5.2.4 on 2025-07-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                ALTER TABLE Users 
                ALTER COLUMN dob TYPE DATE USING dob::DATE
                ''',
            reverse_sql='''
                ALTER TABLE Users
                ALTER COLUMN dob TYPE TIMESTAMP USING dob::TIMESTAMP
                '''
        )
    ]
