# Generated by Django 5.2.4 on 2025-07-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_default_role'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE Users
                ADD COLUMN profile_image VARCHAR(255);
            """,
            reverse_sql="""
                ALTER TABLE Users
                DROP COLUMN profile_image;
            """
        )
    ]
